import fs from 'fs';
const code=[
'import express from "express";',
'import jwt from "jsonwebtoken";',
'import dotenv from "dotenv";',
'import PatientRecord from "../models/PatientRecord.js";',
'dotenv.config();',
'const router=express.Router();',
'const G="https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";',
'const getUser=(req)=>{',
'  try{',
'    const token=req.headers.authorization?.split(" ")[1];',
'    if(!token)return null;',
'    const d=jwt.verify(token,process.env.JWT_SECRET);',
'    return d["id"];',
'  }catch{return null;}',
'};',
'router.post("/analyze",async(req,res)=>{',
'  const userId=getUser(req);',
'  if(!userId)return res.status(401).json({msg:"Unauthorized"});',
'  const{messages,systemPrompt,symptoms,patientName}=req.body;',
'  try{',
'    const contents=messages.map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));',
'    const body={system_instruction:{parts:[{text:systemPrompt||""}]},contents,generationConfig:{maxOutputTokens:1000,temperature:0.4}};',
'    const response=await fetch(G+"?key="+process.env.GEMINI_API_KEY,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});',
'    const data=await response.json();',
'    const result=data.candidates?.[0]?.content?.parts?.[0]?.text||"No response";',
'    await PatientRecord.create({userId,patientName:patientName||"Anonymous",symptoms:symptoms||{},diagnosis:result});',
'    res.json({result});',
'  }catch(err){console.error(err);res.status(500).json({error:"Server error"});}',
'});',
'router.get("/records",async(req,res)=>{',
'  const userId=getUser(req);',
'  if(!userId)return res.status(401).json({msg:"Unauthorized"});',
'  try{const records=await PatientRecord.find({userId}).sort({createdAt:-1});res.json(records);}',
'  catch(err){res.status(500).json({error:"Server error"});}',
'});',
'router.delete("/records/:id",async(req,res)=>{',
'  const userId=getUser(req);',
'  if(!userId)return res.status(401).json({msg:"Unauthorized"});',
'  try{await PatientRecord.findOneAndDelete({_id:req.params.id,userId});res.json({success:true});}',
'  catch(err){res.status(500).json({error:"Server error"});}',
'});',
'export default router;'
].join("\n");
fs.writeFileSync("routes/ulcer.js",code);
console.log("Done!");
